export const bouquets = [
  {
    no: 1,
    color: "",
    product: "Blush Romance",
    price: 49.99,
    description: "Soft pink roses with elegant blooms.",
    image: "./images/shop/secondSection/blush-romance.png",
    imgAlt: "blush-romance",
    review: 17,
    rateTotal: 4,
    condition: "new",
  },
  {
    no: 2,
    color: "",
    product: "Sunny Day",
    price: 49.99,
    description: "Bright sunflowers full of cheerful charm.",
    image: "./images/shop/secondSection/sunny-day.png",
    imgAlt: "sunny-day",
    review: 14,
    rateTotal: 3.5,
    condition: "new",
  },
  {
    no: 3,
    color: "",
    product: "lavender Breeze",
    price: 54.99,
    description: "Relaxing lavender tones with fresh flowers.",
    image: "./images/shop/secondSection/lavender-breeze.png",
    imgAlt: "lavender-breeze",
    review: 18,
    rateTotal: 4,
    condition: "new",
  },
  {
    no: 4,
    color: "",
    product: "Tulip Delight",
    price: 47.99,
    description: "Colorful tulips for joyful celebrations.",
    image: "./images/shop/secondSection/tulip-delight.png",
    imgAlt: "tulip-delight",
    review: 11,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 5,
    color: "",
    product: "Ocean Whisper",
    price: 49.99,
    description: "Cool blue blooms with calming elegance.",
    image: "./images/shop/secondSection/ocean-whisper.png",
    imgAlt: "ocean-whisper",
    review: 28,
    rateTotal: 4.5,
    condition: "best",
  },
  {
    no: 6,
    color: "",
    product: "Passion Bloom",
    price: 59.99,
    description: "Bold red flowers expressing deep love.",
    image: "./images/shop/secondSection/passion-bloom.png",
    imgAlt: "passion-bloom",
    review: 26,
    rateTotal: 4.5,
    condition: "best",
  },
  {
    no: 7,
    color: "",
    product: "Peach Charm",
    price: 46.99,
    description: "Warm peach blossoms with gentle beauty.",
    image: "./images/shop/secondSection/peach-charm.png",
    imgAlt: "peach-charm",
    review: 27,
    rateTotal: 4,
    condition: "best",
  },
  {
    no: 8,
    color: "",
    product: "Wildflower",
    price: 42.99,
    description: "Fresh meadow flowers with natural appeal.",
    image: "./images/shop/secondSection/wild-flower.png",
    imgAlt: "wildflower",
    review: 13,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 9,
    color: "",
    product: "Eternal Love",
    price: 58.99,
    description: "Romantic bouquet crafted for lasting memories.",
    image: "./images/shop/secondSection/eternal-love.png",
    imgAlt: "eternal-love",
    review: 27,
    rateTotal: 4.5,
    condition: "limited",
  },
  {
    no: 10,
    color: "",
    product: "Sweetheart",
    price: 45.99,
    description: "A lovely gift for someone special.",
    image: "./images/shop/secondSection/sweetheart.png",
    imgAlt: "sweetheart",
    review: 21,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 11,
    color: "",
    product: "lily Grace",
    price: 52.99,
    description: "Elegant lilies with timeless sophistication.",
    image: "./images/shop/secondSection/lily-grace.png",
    imgAlt: "lily-grace",
    review: 18,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 12,
    color: "",
    product: "Citrus Splash",
    price: 48.99,
    description: "Vibrant yellow blooms bursting with energy.",
    image: "./images/shop/secondSection/citrus-splash.png",
    imgAlt: "citrus-splash",
    review: 8,
    rateTotal: 2.5,
    condition: "",
  },
  {
    no: 13,
    color: "",
    product: "Midnight Beauty",
    price: 61.99,
    description: "Dark dramatic flowers with luxurious style.",
    image: "./images/shop/secondSection/midnight-beauty.png",
    imgAlt: "midnight-beauty",
    review: 21,
    rateTotal: 4,
    condition: "limited",
  },
  {
    no: 14,
    color: "",
    product: "Rainbow Joy",
    price: 53.99,
    description: "A colorful mix for every occasion.",
    image: "./images/shop/secondSection/rainbow-joy.png",
    imgAlt: "rainbow-joy",
    review: 18,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 15,
    color: "",
    product: "Golden Hour",
    price: 50.99,
    description: "Golden blooms inspired by sunset skies.",
    image: "./images/shop/secondSection/golden-hour.png",
    imgAlt: "golden-hour",
    review: 15,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 16,
    color: "",
    product: "Classic White",
    price: 44.99,
    description: "Pure white flowers with graceful elegance.",
    image: "./images/shop/secondSection/classic-white.png",
    imgAlt: "classic-white",
    review: 16,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 17,
    color: "",
    product: "Berry Bliss",
    price: 49.99,
    description: "Rich berry shades with floral charm.",
    image: "./images/shop/secondSection/berry-bliss.png",
    imgAlt: "berry-bliss",
    review: 20,
    rateTotal: 4,
    condition: "",
  },
  {
    no: 18,
    color: "",
    product: "Soft Pastel",
    price: 47.99,
    description: "Gentle pastel flowers with delicate beauty.",
    image: "./images/shop/secondSection/soft-pastel.png",
    imgAlt: "soft-pastel",
    review: 17,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 19,
    color: "",
    product: "Autumn Glow",
    price: 51.99,
    description: "Warm autumn colors in full bloom.",
    image: "./images/shop/secondSection/autumn-glow.png",
    imgAlt: "autumn-glow",
    review: 20,
    rateTotal: 4,
    condition: "best",
  },
  {
    no: 20,
    color: "",
    product: "Snowflake",
    price: 48.99,
    description: "Crisp white bouquet with winter elegance.",
    image: "./images/shop/secondSection/snowflake.png",
    imgAlt: "snowflake",
    review: 13,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 21,
    color: "",
    product: "Blush Romance 2",
    price: 59.99,
    description: "A luxurious take on our bestseller.",
    image: "./images/shop/secondSection/blush-romance-2.png",
    imgAlt: "blush-romance-2",
    review: 16,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 22,
    color: "",
    product: "Pure Lily Grace",
    price: 49.99,
    description: "Premium lilies with fresh white petals.",
    image: "./images/shop/secondSection/pure-lily-grace.png",
    imgAlt: "pure-lily-grace",
    review: 14,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 23,
    color: "",
    product: "Timeless Love",
    price: 69.99,
    description: "Luxury roses for unforgettable moments.",
    image: "./images/shop/secondSection/timeless-love.png",
    imgAlt: "timeless-love",
    review: 26,
    rateTotal: 4.5,
    condition: "",
  },
  {
    no: 24,
    color: "",
    product: "Sweet Delight",
    price: 54.99,
    description: "Charming blooms with a sweet touch.",
    image: "./images/shop/secondSection/sweet-delight.png",
    imgAlt: "sweet-delight",
    review: 25,
    rateTotal: 4.5,
    condition: "",
  },
  {
    no: 25,
    color: "",
    product: "Sunny Day 2",
    price: 44.99,
    description: "Bright blooms that spread happiness.",
    image: "./images/shop/secondSection/sunny-day-2.png",
    imgAlt: "sunny-day-2",
    review: 17,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 26,
    color: "",
    product: "Purple Elegance",
    price: 49.99,
    description: "Elegant purple flowers with refined beauty.",
    image: "./images/shop/secondSection/purple-elegance.png",
    imgAlt: "purple-elegance",
    review: 13,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 27,
    color: "",
    product: "Garden Bliss",
    price: 59.99,
    description: "Fresh garden flowers in vibrant colors.",
    image: "./images/shop/secondSection/garden-bliss.png",
    imgAlt: "garden-bliss",
    review: 23,
    rateTotal: 4,
    condition: "",
  },
  {
    no: 28,
    color: "",
    product: "Peach Dream",
    price: 49.99,
    description: "Dreamy peach blossoms with soft charm.",
    image: "./images/shop/secondSection/peach-dream.png",
    imgAlt: "peach-dream",
    review: 20,
    rateTotal: 4,
    condition: "",
  },
  {
    no: 29,
    color: "",
    product: "White WHisper",
    price: 54.99,
    description: "Soft white bouquet with peaceful elegance.",
    image: "./images/shop/secondSection/white-whisper.png",
    imgAlt: "white-whisper",
    review: 13,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 30,
    color: "",
    product: "Happy Vibes",
    price: 59.99,
    description: "Bright flowers made to lift spirits.",
    image: "./images/shop/secondSection/happy-vibes.png",
    imgAlt: "happy-vibes",
    review: 16,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 31,
    color: "",
    product: "Pink Perfection",
    price: 64.99,
    description: "Premium pink blooms with timeless elegance.",
    image: "./images/shop/secondSection/pink-perfection.png",
    imgAlt: "pink-perfection",
    review: 25,
    rateTotal: 4.5,
    condition: "best",
  },
  {
    no: 32,
    color: "",
    product: "Ocean Breeze",
    price: 54.99,
    description: "Refreshing blue bouquet inspired by the sea.",
    image: "./images/shop/secondSection/ocean-breeze.png",
    imgAlt: "ocean-breeze",
    review: 25,
    rateTotal: 4.5,
    condition: "best",
  },
  {
    no: 33,
    color: "",
    product: "Red Passion",
    price: 59.99,
    description: "Classic red roses for heartfelt romance.",
    image: "./images/shop/secondSection/red-passion.png",
    imgAlt: "red-passion",
    review: 18,
    rateTotal: 3.5,
    condition: "",
  },
  {
    no: 34,
    color: "",
    product: "Green Harmony",
    price: 49.99,
    description: "Lush greenery with fresh floral accents.",
    image: "./images/shop/secondSection/green-harmony.png",
    imgAlt: "green-harmony",
    review: 23,
    rateTotal: 4,
    condition: "",
  },
  {
    no: 35,
    color: "",
    product: "Golden Tulips",
    price: 44.99,
    description: "Golden tulips full of joyful warmth.",
    image: "./images/shop/secondSection/golden-tulips.png",
    imgAlt: "golden-tulips",
    review: 14,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 36,
    color: "",
    product: "Lavender Dream",
    price: 59.99,
    description: "Elegant lavender bouquet with soothing charm.",
    image: "./images/shop/secondSection/lavender-dream.png",
    imgAlt: "lavender-dream",
    review: 23,
    rateTotal: 4,
    condition: "limited",
  },
  {
    no: 37,
    color: "",
    product: "Daisy Charm",
    price: 39.99,
    description: "Simple daisies with cheerful countryside beauty.",
    image: "./images/shop/secondSection/daisy-charm.png",
    imgAlt: "daisy-charm",
    review: 11,
    rateTotal: 3,
    condition: "",
  },
  {
    no: 38,
    color: "",
    product: "Vibrant Joy",
    price: 49.99,
    description: "A lively bouquet bursting with color.",
    image: "./images/shop/secondSection/vibrant-joy.png",
    imgAlt: "vibrant-joy",
    review: 13,
    rateTotal: 3,
    condition: "",
  },
];
