export const bestSeller = [
  {
    no: 1,
    product: "Passion Bloom",
    price: 59.99,
    description: "Bold red flowers expressing deep love.",
    image: "./images/shop/secondSection/passion-bloom.webp",
    imgAlt: "passion-bloom",
    review: 26,
    rateTotal: 4.5,
    condition: "best",
    category: "rose",
    occasion: ["Birthday", "Valentine's Day", "Mother's Day", "Anniversary"],
    color: "red",
  },
  {
    no: 2,
    product: "Peach Charm",
    price: 46.99,
    description: "Warm peach blossoms with gentle beauty.",
    image: "./images/shop/secondSection/peach-charm.webp",
    imgAlt: "peach-charm",
    review: 27,
    rateTotal: 4,
    condition: "best",
    category: "rose",
    occasion: [
      "Birthday",
      "Valentine's Day",
      "Mother's Day",
      "Anniversary",
      "Sympathy",
    ],
    color: "orange",
  },
  {
    no: 3,
    product: "Autumn Glow",
    price: 51.99,
    description: "Warm autumn colors in full bloom.",
    image: "./images/shop/secondSection/autumn-glow.webp",
    imgAlt: "autumn-glow",
    review: 20,
    rateTotal: 4,
    condition: "best",
    category: "rose",
    occasion: [
      "Birthday",
      "Valentine's Day",
      "Mother's Day",
      "Anniversary",
      "Sympathy",
      "Congratulations",
      "Get Well Soon",
    ],
    color: "orange",
  },
  {
    no: 4,
    product: "Ocean Whisper",
    price: 49.99,
    description: "Cool blue blooms with calming elegance.",
    image: "./images/shop/secondSection/ocean-whisper.webp",
    imgAlt: "ocean-whisper",
    review: 28,
    rateTotal: 4.5,
    condition: "best",
    category: "mix",
    occasion: ["Birthday", "Sympathy", "Mother's Day"],
    color: "blue",
  },
];
